/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author levietdung
 */
public class ContactPanel extends javax.swing.JPanel {
    
    private ArrayList<JPanel> listBtn = new ArrayList<JPanel>();
    private ArrayList<JLabel> listLabel = new ArrayList<JLabel>();
    private int isChoosing = -1;

    public void setIsChoosing(int isChoosing) {
        this.isChoosing = isChoosing;
    }
    private JFrame parentFrame;
    /**
     * Creates new form covid19DiseasePanel
     */
    public ContactPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(204, 204, 204));

        listBtn.add(jPanel2);
        listBtn.add(jPanel3);
        listBtn.add(jPanel4);
        listBtn.add(jPanel6);
        listLabel.add(jLabel1);
        listLabel.add(jLabel2);
        listLabel.add(jLabel3);
        listLabel.add(jLabel4);
        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton1(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredBtn1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitBtn1(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tổ trưởng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton2(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredButton2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton2(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Cán bộ y tế");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton3(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredButton3(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton3(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Hotline xét nghiệm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton4(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredButton4(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton4(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Hotline bộ y tế");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mouseEnteredBtn1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredBtn1
        jPanel2.setBackground(new Color(0,0,204));
        jLabel1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredBtn1

    private void mouseExitBtn1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitBtn1
        if (isChoosing != 0){
            jPanel2.setBackground(new Color(51,102,255));
            jLabel1.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitBtn1

    private void mouseClickButton1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton1
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("Tổ trưởng: Lê Hoàng Nam. Số điện thoại: 0353124142\n" +
                           "Tổ phó: Vũ Thị Thanh. Số điện thoại: 0353123414");
        jPanel2.setBackground(new Color(0,0,204));
        jLabel1.setForeground(new Color(255,255,255));
        isChoosing = 0;
    }//GEN-LAST:event_mouseClickButton1

    private void mouseClickButton2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton2
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("1) Bác sĩ Nguyễn Sơn Tùng - Y tế quận. Số điện thoại: 0345234145\n" +
                           "2) Bác sĩ Trần Hoàng Mai - Y tế quận. Số điện thoại: 0345234145\n" +
                           "3) Bác sĩ Nguyễn Lan - Y tế phường. Số điện thoại: 0345324989\n" +
                           "4) Bác sĩ Trần Văn Nam - Y tế phường. Số điện thoại: 0345212398\n\n"
                           );
        jPanel3.setBackground(new Color(0,0,204));
        jLabel2.setForeground(new Color(255,255,255));
        isChoosing = 1;
    }//GEN-LAST:event_mouseClickButton2

    private void mouseEnteredButton2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredButton2
        jPanel3.setBackground(new Color(0,0,204));
        jLabel2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredButton2

    private void mouseExitButton2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton2
        if (isChoosing != 1){
            jPanel3.setBackground(new Color(51,102,255));
            jLabel2.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitButton2

    private void mouseClickButton3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton3
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("1) Bệnh viện Bạch Mai: 0969.851.616\n" +
                           "2) Bệnh viện Nhiệt đới Trung ương: 0969.241.616\n" +
                           "3) Bệnh viện Xanh Pôn Hà Nội: 0904.138.502\n" +
                           "4) Bệnh viện E: 0912.168.887\n" +
                           "5) Bệnh viện Nhi Trung ương: 0372.884.712\n" +
                           "6) Bệnh viện Phổi Trung ương: 0967.941.616\n" +
                           "7) Bệnh viện Vinmec Hà Nội: 0934.472.768\n" +
                           "8) Bệnh viện Việt Nam - Thụy Điển Uông Bí: 0966.681.313\n" 
                           );
        jPanel4.setBackground(new Color(0,0,204));
        jLabel3.setForeground(new Color(255,255,255));
        isChoosing = 2;
    }//GEN-LAST:event_mouseClickButton3

    private void mouseEnteredButton3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredButton3
        jPanel4.setBackground(new Color(0,0,204));
        jLabel3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredButton3

    private void mouseExitButton3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton3
        if (isChoosing != 2){
            jPanel4.setBackground(new Color(51,102,255));
            jLabel3.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitButton3

    private void mouseClickButton4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton4
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("1900.9095"
                           );        
        jPanel6.setBackground(new Color(0,0,204));
        jLabel4.setForeground(new Color(255,255,255));
        isChoosing = 3;
    }//GEN-LAST:event_mouseClickButton4

    private void mouseEnteredButton4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredButton4
        jPanel6.setBackground(new Color(0,0,204));
        jLabel4.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredButton4

    private void mouseExitButton4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton4
        if (isChoosing != 3){   
            jPanel6.setBackground(new Color(51,102,255));
            jLabel4.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitButton4


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextArea1;
    // End of variables declaration//GEN-END:variables
}
