/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author levietdung
 */
public class Covid19DiseasePanel extends javax.swing.JPanel {
    
    private ArrayList<JPanel> listBtn = new ArrayList<JPanel>();
    private ArrayList<JLabel> listLabel = new ArrayList<JLabel>();
    private int isChoosing = -1;

    public void setIsChoosing(int isChoosing) {
        this.isChoosing = isChoosing;
    }
    private JFrame parentFrame;
    /**
     * Creates new form covid19DiseasePanel
     */
    public Covid19DiseasePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(204, 204, 204));

        listBtn.add(jPanel2);
        listBtn.add(jPanel3);
        listBtn.add(jPanel4);
        listBtn.add(jPanel6);
        listBtn.add(jPanel8);
        listBtn.add(jPanel10);
        listLabel.add(jLabel1);
        listLabel.add(jLabel2);
        listLabel.add(jLabel3);
        listLabel.add(jLabel4);
        listLabel.add(jLabel7);
        listLabel.add(jLabel5);
        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton1(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredBtn1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitBtn1(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Khái niệm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton2(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredButton2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton2(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nguồn gốc");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton3(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredButton3(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton3(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Tác hại");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton4(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredButton4(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton4(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Lây nhiễm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(51, 102, 255));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton5(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredBtn5(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitBtn5(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Triệu chứng");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBackground(new java.awt.Color(51, 102, 255));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickButton6(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredButton6(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton6(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Phòng tránh");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mouseEnteredBtn1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredBtn1
        jPanel2.setBackground(new Color(0,0,204));
        jLabel1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredBtn1

    private void mouseExitBtn1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitBtn1
        if (isChoosing != 0){
            jPanel2.setBackground(new Color(51,102,255));
            jLabel1.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitBtn1

    private void mouseClickButton1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton1
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("1) Dịch Covid-19 viết tắt của cụm từ \"Coronavirrus disease\" 2019, là dịch bệnh do virus\n" + 
                   "corona gây ra và xuất hiện lần đầu năm 2019.\n" +
                   "2) Dịch bệnh này xuất hiện đầu tiên ở thành phố Vũ Hán, tỉnh Hồ Bắc, Trung Quốc, trong\n" +
                   "đó nhiều người cùng bị viêm đường hô hấp cấp. Tác nhân gây bệnh sau đó được xác định\n" +
                   "là một chủng mới của virus Corona. Chủng virus mới này được tìm ra năm 2019 nên được\n" + 
                   "ký hiệu là 2019-nCoV .Vì thế ban đầu, dịch bệnh này có tên là \"Dịch viêm đường hô hấp\n" +
                   "cấp do chủng mới của virus Corona 2019-nCoV\"");
        jPanel2.setBackground(new Color(0,0,204));
        jLabel1.setForeground(new Color(255,255,255));
        isChoosing = 0;
    }//GEN-LAST:event_mouseClickButton1

    private void mouseClickButton2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton2
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("1) WHO cũng như các chuyên gia y tế trên toàn thế giới đang nỗ lực xác định nguồn gốc\n" +
                           "của SARS-CoV-2. Nhiều ý kiến cho rằng, vi rút Corona là một Betacoronavirus, thuộc họ\n" +
                           "với virus gây hội chứng MERS-CoV và hội chứng SARS, tất cả có nguồn gốc từ vật chủ là\n" +
                           "loài dơi.\n" +
                           "2) Phân tích cây di truyền của vi rút này đang được tiếp tục để biết nguồn gốc cụ thể của vi rút.\n"
                           );
        jPanel3.setBackground(new Color(0,0,204));
        jLabel2.setForeground(new Color(255,255,255));
        isChoosing = 1;
    }//GEN-LAST:event_mouseClickButton2

    private void mouseEnteredButton2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredButton2
        jPanel3.setBackground(new Color(0,0,204));
        jLabel2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredButton2

    private void mouseExitButton2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton2
        if (isChoosing != 1){
            jPanel3.setBackground(new Color(51,102,255));
            jLabel2.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitButton2

    private void mouseClickButton3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton3
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("Theo Điều 3 Luật Phòng, chống bệnh truyền nhiễm, các bệnh truyền nhiễm được phân\n" +
                           "chia làm 3 nhóm:\n" +
                           "1) Nhóm A: Là những bệnh truyền nhiễm đặc biệt nguy hiểm; lây truyền nhanh; phát tán\n" +
                           "rộng; tỷ lệ tử vong cao hoặc chưa rõ tác nhân gây bệnh.\n" +
                           "2) Nhóm B: Là các bệnh truyền nhiễm nguy hiểm, có khả năng lây truyền nhanh và có thể\n" +
                           "gây tử vong.\n" +
                           "3) Nhóm C: Là các bệnh ít nguy hiểm, khả năng lây truyền không nhanh và ít gây tử vong.\n" +
                           "Trên cơ sở đó, dịch Covid-19 được Bộ Y tế xếp vào nhóm A - nguy hiểm vì bệnh có khả\n" +
                           "năng lây lan nhanh trong cộng đồng, chưa có thuốc điều trị đặc hiệu và cũng chưa có\n" +
                           "vacxin phòng bệnh, tỷ lệ tử vong ban đầu được dự báo tới 5%");
        jPanel4.setBackground(new Color(0,0,204));
        jLabel3.setForeground(new Color(255,255,255));
        isChoosing = 2;
    }//GEN-LAST:event_mouseClickButton3

    private void mouseEnteredButton3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredButton3
        jPanel4.setBackground(new Color(0,0,204));
        jLabel3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredButton3

    private void mouseExitButton3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton3
        if (isChoosing != 2){
            jPanel4.setBackground(new Color(51,102,255));
            jLabel3.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitButton3

    private void mouseClickButton4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton4
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("1) Hầu hết các loại SARS-CoV-2 có con đường lây truyền giống như những loại virus gây\n" +
                           "cảm lạnh khác, đó là:\n" +
                           "    - Người bệnh ho và hắt hơi mà không che miệng, dẫn tới phát tán các giọt nước vào\n" +
                           "    không khí, làm lây lan virus sang người khỏe mạnh.\n" +
                           "    - Người khỏe mạnh chạm/bắt tay với người có SARS-CoV-2 khiến virus truyền từ\n" +
                           "    người này sang người khác.\n" +
                           "    - Người khỏe mạnh tiếp xúc với một bề mặt hoặc vật thể có virus, sau đó đưa tay lên\n" +
                           "    mũi, mắt hoặc miệng của mình.\n" +
                           "    - Trong những trường hợp hiếm hoi, virus Corona có thể lây lan qua tiếp xúc với phân.\n" +
                           "2) Virus này ban đầu có thể xuất hiện từ nguồn động vật nhưng hiện nay đã lây lan từ\n" +
                           "người sang người. Các nhà khoa học Trung Quốc cho biết, trung bình một bệnh nhân\n" +
                           "nhiễm SARS-CoV-2 sẽ lây lan sang 6 người khác. Chính vì SARS-CoV-2 có khả năng lan\n" + 
                           "truyền rất nhanh từ người sang người, nên nếu người dân không được trang bị kiến\n" +
                           "thức về phòng chống bệnh, đại dịch rất dễ xảy ra.");        
        jPanel6.setBackground(new Color(0,0,204));
        jLabel4.setForeground(new Color(255,255,255));
        isChoosing = 3;
    }//GEN-LAST:event_mouseClickButton4

    private void mouseEnteredButton4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredButton4
        jPanel6.setBackground(new Color(0,0,204));
        jLabel4.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredButton4

    private void mouseExitButton4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton4
        if (isChoosing != 3){   
            jPanel6.setBackground(new Color(51,102,255));
            jLabel4.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitButton4

    private void mouseClickButton5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton5
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("");
        jTextArea1.insertIcon(new ImageIcon("/Users/levietdung/Desktop/Screen Shot 2020-11-24 at 13.25.51.png"));
        jPanel8.setBackground(new Color(0,0,204));
        jLabel7.setForeground(new Color(255,255,255));
        isChoosing = 4;
    }//GEN-LAST:event_mouseClickButton5

    private void mouseEnteredBtn5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredBtn5
        jPanel8.setBackground(new Color(0,0,204));
        jLabel7.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredBtn5

    private void mouseExitBtn5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitBtn5
        if (isChoosing != 4){   
            jPanel8.setBackground(new Color(51,102,255));
            jLabel7.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitBtn5

    private void mouseClickButton6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickButton6
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(new Color(51,102,255));
            listLabel.get(isChoosing).setForeground(new Color(204,204,204));
        }
        jTextArea1.setText("");
        jTextArea1.insertIcon(new ImageIcon("/Users/levietdung/Desktop/Untitled 2.png"));
        jPanel10.setBackground(new Color(0,0,204));
        jLabel5.setForeground(new Color(255,255,255));
        isChoosing = 5;
    }//GEN-LAST:event_mouseClickButton6

    private void mouseEnteredButton6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredButton6
        jPanel10.setBackground(new Color(0,0,204));
        jLabel5.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mouseEnteredButton6

    private void mouseExitButton6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton6
        if (isChoosing != 5){   
            jPanel10.setBackground(new Color(51,102,255));
            jLabel5.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_mouseExitButton6


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextArea1;
    // End of variables declaration//GEN-END:variables
}
