/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.HealthDeclarationPanelController;
import controllers.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author levietdung
 */
public class HealthDeclarationPanel extends javax.swing.JPanel {
    private JFrame parentFrame;
    private HealthDeclarationPanelController controller;
    /**
     * Creates new form HealthDeclarationPanel
     */
    public HealthDeclarationPanel(JFrame parentFrame) { 
        this.parentFrame = parentFrame;
        this.controller = new HealthDeclarationPanelController();
        initComponents();
    }

    public JTextField getIDField() {
        return IDField;
    }

    public JCheckBox getBloodRelatedDiseaseField() {
        return bloodRelatedDiseaseField;
    }

    public JCheckBox getCancerField() {
        return cancerField;
    }

    public JCheckBox getCoughField() {
        return coughField;
    }

    public JCheckBox getDiabetesFIeld() {
        return diabetesFIeld;
    }

    public JRadioButton getDontHavePregnantButton() {
        return dontHavePregnantButton;
    }

    public JTextField getEmailField() {
        return emailField;
    }

    public JCheckBox getFeverField() {
        return feverField;
    }

    public JCheckBox getFromInfectedCountryField() {
        return fromInfectedCountryField;
    }

    public JRadioButton getHavePregnantButton() {
        return havePregnantButton;
    }

    public JCheckBox getHaveSymptomsField() {
        return haveSymptomsField;
    }

    public JCheckBox getHeartRelatedDiseaseField() {
        return heartRelatedDiseaseField;
    }

    public JCheckBox getHepatitisField() {
        return hepatitisField;
    }

    public JCheckBox getHighBloodPressureField() {
        return highBloodPressureField;
    }

    public JCheckBox getImmunodeficiencyField() {
        return immunodeficiencyField;
    }

    public JTextField getjTextField3() {
        return addressField;
    }

    public JCheckBox getKidneyDisease() {
        return kidneyDisease;
    }

    public JCheckBox getLungDiseaseField() {
        return lungDiseaseField;
    }

    public JCheckBox getMeetInfectedField() {
        return meetInfectedField;
    }

    public JTextField getNameField() {
        return nameField;
    }

    public JTextField getPhoneNumberField() {
        return phoneNumberField;
    }

    public JCheckBox getPneumoniaField() {
        return pneumoniaField;
    }

    public JCheckBox getShoreThroatField() {
        return shoreThroatField;
    }

    public JCheckBox getStuffyField() {
        return stuffyField;
    }

    public JCheckBox getTiredField() {
        return tiredField;
    }

    public JCheckBox getTransplantField() {
        return transplantField;
    }

    public JTextArea getTravellingHistoryField() {
        return travellingHistoryField;
    }

    public JCheckBox getHaveHealthInsuranceField() {
        return haveHealthInsuranceField;
    }

    public JTextField getAddressField() {
        return addressField;
    }
    
    public JComboBox<String> getDistrictBox() {
        return districtBox;
    }

    public JComboBox<String> getProvinceBox() {
        return provinceBox;
    }

    public JComboBox<String> getWardBox() {
        return wardBox;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        haveHealthInsuranceField = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        districtBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        provinceBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        wardBox = new javax.swing.JComboBox<>();
        emailField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        feverField = new javax.swing.JCheckBox();
        coughField = new javax.swing.JCheckBox();
        stuffyField = new javax.swing.JCheckBox();
        pneumoniaField = new javax.swing.JCheckBox();
        shoreThroatField = new javax.swing.JCheckBox();
        tiredField = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        meetInfectedField = new javax.swing.JCheckBox();
        fromInfectedCountryField = new javax.swing.JCheckBox();
        haveSymptomsField = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        hepatitisField = new javax.swing.JCheckBox();
        heartRelatedDiseaseField = new javax.swing.JCheckBox();
        immunodeficiencyField = new javax.swing.JCheckBox();
        lungDiseaseField = new javax.swing.JCheckBox();
        diabetesFIeld = new javax.swing.JCheckBox();
        bloodRelatedDiseaseField = new javax.swing.JCheckBox();
        kidneyDisease = new javax.swing.JCheckBox();
        highBloodPressureField = new javax.swing.JCheckBox();
        transplantField = new javax.swing.JCheckBox();
        cancerField = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        havePregnantButton = new javax.swing.JRadioButton();
        dontHavePregnantButton = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        travellingHistoryField = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        fillForFamilyMemField = new javax.swing.JRadioButton();

        buttonGroup1.add(havePregnantButton);
        buttonGroup1.add(dontHavePregnantButton);

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        setPreferredSize(new java.awt.Dimension(877, 481));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText(" Năm sinh:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText(" Quận/huyện:");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText(" Điện thoại:");

        haveHealthInsuranceField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        haveHealthInsuranceField.setText("Có thẻ bảo hiểm y tế");
        haveHealthInsuranceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haveHealthInsuranceFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText(" Số hộ chiếu / CMND / CCCD");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText(" Tỉnh thành:");

        nameField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nameField.setText(LoginController.currentPersonalInfo.getHoTen().toUpperCase());
        nameField.setEditable(false);

        addressField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        districtBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                districtBoxItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Quốc tịch:");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Giới tính:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText(" Địa chỉ liên lạc tại Việt Nam:");

        provinceBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                provinceBoxItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText(" Họ và tên (ghi chữ IN HOA):");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setText(" Trong 21 ngày qua, Anh/chị có đến Quốc gia/Vùng lãnh thổ nào không?");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText(" Số nhà, phố, tổ dân phố/thôn/đội");

        IDField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        IDField.setText(LoginController.currentPersonalInfo.getSoHoChieu());
        IDField.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText(" Phường/xã:");

        phoneNumberField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        phoneNumberField.setText(LoginController.currentPersonalInfo.getSoDienThoai());
        phoneNumberField.setEditable(false);

        try {
            controller.setAddressBox(this);
        } catch (Exception e){
            e.printStackTrace();
        }

        emailField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        emailField.setText(LoginController.currentPersonalInfo.getEmail());
        emailField.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel15.setText(" Trong 21 ngày qua, Anh/chị có thấy xuất hiện dấu hiệu nào sau đây không?");

        feverField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        feverField.setText("Sốt");
        feverField.setToolTipText("");
        feverField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feverFieldActionPerformed(evt);
            }
        });

        coughField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        coughField.setText("Ho");
        coughField.setToolTipText("");
        coughField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coughFieldActionPerformed(evt);
            }
        });

        stuffyField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        stuffyField.setText("Khó thở");
        stuffyField.setToolTipText("");
        stuffyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuffyFieldActionPerformed(evt);
            }
        });

        pneumoniaField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pneumoniaField.setText("Viêm phổi");
        pneumoniaField.setToolTipText("");
        pneumoniaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pneumoniaFieldActionPerformed(evt);
            }
        });

        shoreThroatField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        shoreThroatField.setText("Đau họng");
        shoreThroatField.setToolTipText("");
        shoreThroatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoreThroatFieldActionPerformed(evt);
            }
        });

        tiredField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tiredField.setText("Mệt mỏi");
        tiredField.setToolTipText("");
        tiredField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiredFieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel16.setText(" Trong 21 ngày qua, Anh/chị có tiếp xúc với?");

        meetInfectedField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        meetInfectedField.setText("Người bệnh, hoặc nghi ngờ mắc COVID-19");

        fromInfectedCountryField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fromInfectedCountryField.setText("Người từ nước có COVID-19");

        haveSymptomsField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        haveSymptomsField.setText("Người có biểu hiện (sốt, ho, khó thở, viêm phổi)");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel17.setText(" Hiện Anh/chị có bị bệnh nào dưới đây?");

        hepatitisField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        hepatitisField.setText("Bệnh gan mãn tính");

        heartRelatedDiseaseField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        heartRelatedDiseaseField.setText("Bệnh tim mạch");

        immunodeficiencyField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        immunodeficiencyField.setText("Suy giảm miễn dịch");

        lungDiseaseField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lungDiseaseField.setText("Bệnh phổi mãn tính");
        lungDiseaseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lungDiseaseFieldActionPerformed(evt);
            }
        });

        diabetesFIeld.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        diabetesFIeld.setText("Tiểu đường");

        bloodRelatedDiseaseField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bloodRelatedDiseaseField.setText("Bệnh máu mãn tính");

        kidneyDisease.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        kidneyDisease.setText("Bệnh thận mãn tính");

        highBloodPressureField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        highBloodPressureField.setText("Huyết áp cao");

        transplantField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        transplantField.setText("Người nhận ghép tạng, thuỷ xương");

        cancerField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cancerField.setText("Ung thư");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setText(" Bạn có đang ở trong thời kỳ hay không?");

        jButton1.setText("Xác nhận");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirm(evt);
            }
        });

        havePregnantButton.setText("Có");

        dontHavePregnantButton.setText("Không");

        travellingHistoryField.setColumns(20);
        travellingHistoryField.setRows(5);
        jScrollPane2.setViewportView(travellingHistoryField);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(141, 141, 141))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IDField)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(102, 102, 102)
                        .addComponent(havePregnantButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dontHavePregnantButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hepatitisField)
                            .addComponent(lungDiseaseField)
                            .addComponent(heartRelatedDiseaseField)
                            .addComponent(immunodeficiencyField)
                            .addComponent(diabetesFIeld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloodRelatedDiseaseField)
                            .addComponent(kidneyDisease)
                            .addComponent(highBloodPressureField)
                            .addComponent(transplantField)
                            .addComponent(cancerField))))
                .addGap(105, 105, 105))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel5)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel9)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(haveHealthInsuranceField)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(emailField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(provinceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(districtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(wardBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(feverField)
                        .addGap(18, 18, 18)
                        .addComponent(coughField)
                        .addGap(18, 18, 18)
                        .addComponent(stuffyField)
                        .addGap(18, 18, 18)
                        .addComponent(pneumoniaField)
                        .addGap(18, 18, 18)
                        .addComponent(shoreThroatField)
                        .addGap(18, 18, 18)
                        .addComponent(tiredField))
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meetInfectedField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromInfectedCountryField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(haveSymptomsField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(haveHealthInsuranceField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinceBox, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(districtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(wardBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feverField)
                    .addComponent(coughField)
                    .addComponent(stuffyField)
                    .addComponent(pneumoniaField)
                    .addComponent(shoreThroatField)
                    .addComponent(tiredField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meetInfectedField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromInfectedCountryField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(haveSymptomsField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hepatitisField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lungDiseaseField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heartRelatedDiseaseField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(immunodeficiencyField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diabetesFIeld))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bloodRelatedDiseaseField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kidneyDisease)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(highBloodPressureField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transplantField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancerField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(havePregnantButton)
                    .addComponent(dontHavePregnantButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        jScrollPane1.setViewportView(jPanel1);

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KHAI BÁO Y TẾ CÁ NHÂN");

        fillForFamilyMemField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fillForFamilyMemField.setText("Khai báo cho người thân");
        fillForFamilyMemField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fillForFamilyMemField(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fillForFamilyMemField)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(fillForFamilyMemField)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void haveHealthInsuranceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haveHealthInsuranceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haveHealthInsuranceFieldActionPerformed

    private void feverFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feverFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feverFieldActionPerformed

    private void coughFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coughFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coughFieldActionPerformed

    private void stuffyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuffyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuffyFieldActionPerformed

    private void pneumoniaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pneumoniaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pneumoniaFieldActionPerformed

    private void shoreThroatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoreThroatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shoreThroatFieldActionPerformed

    private void tiredFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiredFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiredFieldActionPerformed

    private void lungDiseaseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lungDiseaseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lungDiseaseFieldActionPerformed

    private void provinceBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_provinceBoxItemStateChanged
        try {
            controller.setDistrictBox(this);
        } catch (SQLException ex) {
            Logger.getLogger(HealthDeclarationPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HealthDeclarationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_provinceBoxItemStateChanged

    private void districtBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_districtBoxItemStateChanged
        try {
            controller.setWardBox(this);
        } catch (SQLException ex) {
            Logger.getLogger(HealthDeclarationPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HealthDeclarationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_districtBoxItemStateChanged

    private void confirm(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirm
        try {
            controller.confirmForm(this);
        } catch (SQLException ex) {
            Logger.getLogger(HealthDeclarationPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HealthDeclarationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirm

    private void fillForFamilyMemField(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fillForFamilyMemField
        if (fillForFamilyMemField.isSelected()){
            nameField.setEditable(true);
            IDField.setEditable(true);
            phoneNumberField.setEditable(true);
            emailField.setEditable(true);
            nameField.setText("");
            IDField.setText("");
            phoneNumberField.setText("");;
            emailField.setText("");
        } else {
            nameField.setEditable(false);
            IDField.setEditable(false);
            phoneNumberField.setEditable(false);
            emailField.setEditable(false);
            nameField.setText(LoginController.currentPersonalInfo.getHoTen());
            IDField.setText(LoginController.currentPersonalInfo.getSoHoChieu());
            phoneNumberField.setText(LoginController.currentPersonalInfo.getSoDienThoai());;
            emailField.setText(LoginController.currentPersonalInfo.getEmail());
        }
    }//GEN-LAST:event_fillForFamilyMemField

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField addressField;
    private javax.swing.JCheckBox bloodRelatedDiseaseField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cancerField;
    private javax.swing.JCheckBox coughField;
    private javax.swing.JCheckBox diabetesFIeld;
    private javax.swing.JComboBox<String> districtBox;
    private javax.swing.JRadioButton dontHavePregnantButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JCheckBox feverField;
    private javax.swing.JRadioButton fillForFamilyMemField;
    private javax.swing.JCheckBox fromInfectedCountryField;
    private javax.swing.JCheckBox haveHealthInsuranceField;
    private javax.swing.JRadioButton havePregnantButton;
    private javax.swing.JCheckBox haveSymptomsField;
    private javax.swing.JCheckBox heartRelatedDiseaseField;
    private javax.swing.JCheckBox hepatitisField;
    private javax.swing.JCheckBox highBloodPressureField;
    private javax.swing.JCheckBox immunodeficiencyField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox kidneyDisease;
    private javax.swing.JCheckBox lungDiseaseField;
    private javax.swing.JCheckBox meetInfectedField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JCheckBox pneumoniaField;
    private javax.swing.JComboBox<String> provinceBox;
    private javax.swing.JCheckBox shoreThroatField;
    private javax.swing.JCheckBox stuffyField;
    private javax.swing.JCheckBox tiredField;
    private javax.swing.JCheckBox transplantField;
    private javax.swing.JTextArea travellingHistoryField;
    private javax.swing.JComboBox<String> wardBox;
    // End of variables declaration//GEN-END:variables
}
