/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LoginController;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import services.MysqlConnection;

/**
 *
 * @author levietdung
 */
public class InboxPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendQuestionPanel
     */
    private OtherQuestionPanel parentPanel;
    
    public InboxPanel(OtherQuestionPanel parentPanel) {
        this.parentPanel = parentPanel;
        initComponents();
    }

    public OtherQuestionPanel getParentPanel() {
        return parentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(227, 240, 245));
        setPreferredSize(new java.awt.Dimension(649, 440));
        setSize(new java.awt.Dimension(677, 481));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(677, 481));
        jScrollPane2.setSize(new java.awt.Dimension(677, 481));

        jPanel1.setPreferredSize(new java.awt.Dimension(677, 481));
        jPanel1.setSize(new java.awt.Dimension(677, 481));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        int counter = 0;
        try{
            Connection connection = MysqlConnection.getMysqlConnection();
            Statement st = connection.createStatement();
            String sql = "SELECT * FROM `questionsAndAnswers`, `MedicalStaff` WHERE MedicalStaff.ID = questionsAndAnswers.AnswererID AND `SenderID` = " + LoginController.currentUser.getIDNhanKhau();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                QuestionPanel panel = new QuestionPanel(rs.getInt("SenderID") + "",LoginController.currentPersonalInfo.getHoTen(),rs.getString("Name"),rs.getString("Question"), rs.getString("sendTime"), rs.getString("sendDate"),rs.getString("Subject"),this,rs.getString("isAnswered"), rs.getString("answeredTime"), rs.getString("answeredDate"), rs.getString("Answer"));
                jPanel1.add(panel);
                counter++;
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        if (counter < 13){
            for (int i = 0; i < 20-counter; i++){
                JPanel extendPanel = new JPanel();
                extendPanel.setSize(new Dimension(645,35));
                jPanel1.add(extendPanel);
            }
        }

        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
