/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.QuestionAndAnswerPanelController;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import models.KhaiBaoYTe;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import controllers.MedicalManagementController;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import utility.Calendar;


/**
 *
 * @author Admin
 */
public class MedicalManagement extends javax.swing.JPanel {
    private final MedicalManagementController controller;
    private JFrame parentJFrame;
    DefaultTableModel tableModel;

    /**
     * Creates new form QuestionAndAnswerPanel
     */
    
    private final JFrame parentFrame;
    
    
    public MedicalManagement(JFrame parentFrame) throws ClassNotFoundException {
        this.parentFrame = parentFrame;
        initComponents();
        controller = new MedicalManagementController();
        tableModel = (DefaultTableModel) jTable2.getModel();
        jTable2.setRowHeight(jTable2.getRowHeight()+20);
        showKhaiBaoYTe(controller.findAll());
    }
    
    private void showKhaiBaoYTe(List<KhaiBaoYTe> khaibaoytelist) throws ClassNotFoundException, ClassNotFoundException{
        for (KhaiBaoYTe k: khaibaoytelist){
            tableModel.addRow(new Object[] {"" + k.getID(), k.getStatus(), k.getInfectedFrom(), k.getRecoveredConfirm(), k.getTreatingPlace(), k.getQuarantineStartDate(), k.getQuarantineFinishDate(), k.getQuarantinePlace()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ THÔNG TIN Y TẾ");

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Status", "InfectedFrom", "RecoveredConfirm", "TreatingPlace", "QuarantineStartDate", "QuarantineFinishDate", "QuarantinePlace"
            }
        ));
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(17);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(106);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(79);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(107);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(115);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(122);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(130);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable2.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        jTable2.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        Color color = UIManager.getColor("Table.gridColor");
        MatteBorder border = new MatteBorder(1, 1, 0, 0, color);
        jTable2.setBorder(border);
        jTable2.setCellSelectionEnabled (false);
        jTable2.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Tình trạng bệnh:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL", "Chưa nhiễm bệnh", "Đang cách ly", "Đã nhiễm bệnh" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chooseStatus(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Ngày bắt đầu cách ly:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Ngày bắt đầu cách ly:");

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectQuarantineStartDay(evt);
            }
        });

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectQuarantineFinishDay(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Ngày bắt đầu nhiễm bệnh:");

        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectInfectedStartDay(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Ngày khỏi bệnh:");

        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectInfectedFinishDay(evt);
            }
        });

        jButton1.setText("Tìm kiếm");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jTextField4))))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(234, 234, 234))))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(339, 339, 339))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }
    
    private void chooseStatus(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chooseStatus
        if (jComboBox1.getSelectedItem().equals("Đang cách ly")){
            jLabel3.setFont(new Font("Lucida Grande", 1, 14));
            jLabel4.setFont(new Font("Lucida Grande", 1, 14));
            jLabel5.setFont(new Font("Lucida Grande", 0, 14));
            jLabel6.setFont(new Font("Lucida Grande", 0, 14));
            jTextField1.setEnabled(true);
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField3.setText("");
            jTextField4.setText("");
        } else if (jComboBox1.getSelectedItem().equals("Đã nhiễm bệnh")){
            jLabel3.setFont(new Font("Lucida Grande", 0, 14));
            jLabel4.setFont(new Font("Lucida Grande", 0, 14));
            jLabel5.setFont(new Font("Lucida Grande", 1, 14));
            jLabel6.setFont(new Font("Lucida Grande", 1, 14));
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setEnabled(true);
            jTextField4.setEnabled(true);
        } else if (jComboBox1.getSelectedItem().equals("Chưa nhiễm bệnh") ||
                   jComboBox1.getSelectedItem().equals("NULL")){
            jLabel3.setFont(new Font("Lucida Grande", 0, 14));
            jLabel4.setFont(new Font("Lucida Grande", 0, 14));
            jLabel5.setFont(new Font("Lucida Grande", 0, 14));
            jLabel6.setFont(new Font("Lucida Grande", 0, 14));
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField3.setText("");
            jTextField4.setText("");
        }
    }//GEN-LAST:event_chooseStatus

    private void search(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search
        try {
            tableModel.setRowCount(0);
            showKhaiBaoYTe(controller.findFilter(this));
            jTable2.validate();
            jTable2.repaint();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MedicalManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_search

    private void selectQuarantineStartDay(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectQuarantineStartDay
        Calendar.popUp(jTextField1);
    }//GEN-LAST:event_selectQuarantineStartDay

    private void selectQuarantineFinishDay(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectQuarantineFinishDay
        Calendar.popUp(jTextField2);
    }//GEN-LAST:event_selectQuarantineFinishDay

    private void selectInfectedStartDay(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectInfectedStartDay
        Calendar.popUp(jTextField3);
    }//GEN-LAST:event_selectInfectedStartDay

    private void selectInfectedFinishDay(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectInfectedFinishDay
        Calendar.popUp(jTextField4);
    }//GEN-LAST:event_selectInfectedFinishDay

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
