/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author levietdung
 */
public class QuestionPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestionPanel
     * @param questionID
     * @param senderName
     * @param time
     * @param subject
     */
    private String questionIDString;
    private String senderNameString;
    private String answererNameString;
    private String sendTimeString;
    private String answerTimeString;
    private String subjectString;
    private String isAnsweredString;
    private String sendDateString;
    private String answerDateString;
    private String questionString;
    private String answerString;
    private InboxPanel parentPanel;
    
    public QuestionPanel(String questionID, String senderName, String answererName, String question, String sendTime, String sendDate, String subject, 
                         InboxPanel parentPanel, String isAnswered, String answerTime, String answerDate, String answer) {
        questionIDString = questionID;
        senderNameString = senderName;
        answererNameString = answererName;
        sendTimeString = sendTime;
        subjectString = subject;
        isAnsweredString = isAnswered;
        sendDateString = sendDate;
        answerTimeString = answerTime;
        answerDateString = answerDate;
        answerString = answer;
        questionString = question;
        this.parentPanel = parentPanel;
        initComponents();
    }  

    public String getQuestionIDString() {
        return questionIDString;
    }

    public String getSenderNameString() {
        return senderNameString;
    }

    public String getTimeString() {
        return sendTimeString;
    }

    public String getSubjectString() {
        return subjectString;
    }

    public String getIsAnsweredString() {
        return isAnsweredString;
    }

    public InboxPanel getParentPanel() {
        return parentPanel;
    }

    public String getAnswerTimeString() {
        return answerTimeString;
    }

    public String getAnswerDateString() {
        return answerDateString;
    }

    public String getSendTimeString() {
        return sendTimeString;
    }

    public String getSendDateString() {
        return sendDateString;
    }

    public JLabel getSenderName() {
        return senderName;
    }

    public String getAnswerString() {
        return answerString;
    }

    public String getQuestionString() {
        return questionString;
    }

    public String getAnswererNameString() {
        return answererNameString;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senderName = new javax.swing.JLabel();
        questionID = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setMinimumSize(new java.awt.Dimension(677, 35));
        setPreferredSize(new java.awt.Dimension(677, 35));
        setSize(new java.awt.Dimension(677, 35));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedOnQuestion(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnteredQuestion(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitedQuestion(evt);
            }
        });

        senderName.setText(senderNameString);
        questionID.setText(questionIDString);
        subject.setText(subjectString);
        time.setText(sendTimeString + " " + sendDateString);

        if (isAnsweredString.equals("True")){
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/checked.png")));
        } else {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pending.png")));
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(questionID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senderName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(questionID, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(senderName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mouseEnteredQuestion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnteredQuestion
        this.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_mouseEnteredQuestion

    private void mouseExitedQuestion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitedQuestion
        this.setBackground(new Color(238,238,238));
    }//GEN-LAST:event_mouseExitedQuestion

    private void mouseClickedOnQuestion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedOnQuestion
        parentPanel.setVisible(false);
        parentPanel.setEnabled(false);
        QuestionContentPanel panel = new QuestionContentPanel(this);
        parentPanel.getParentPanel().getjPanel5().add(panel);
        parentPanel.getParentPanel().getjPanel5().validate();
        parentPanel.getParentPanel().getjPanel5().repaint();
    }//GEN-LAST:event_mouseClickedOnQuestion

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel questionID;
    private javax.swing.JLabel senderName;
    private javax.swing.JLabel subject;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
