/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.QuestionAndAnswerPanelController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author levietdung
 */
public class QuestionAndAnswerPanel extends javax.swing.JPanel {
    private JFrame parentFrame;
    private QuestionAndAnswerPanelController controller;
    private ArrayList<JPanel> listBtn = new ArrayList<JPanel>();
    private ArrayList<JLabel> listLabel = new ArrayList<JLabel>();
    private int isChoosing = -1;
    private Color color1 = new Color(85,119,186);
    private Color color2 = new Color(241,244,249);
    private Color color3 = new Color(65,103,179);
    private Color color4 = new Color(121,147,201);
    /**
     * Creates new form QuestionAndAnswerPanel
     */
    public QuestionAndAnswerPanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        this.controller = new QuestionAndAnswerPanelController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setPreferredSize(new java.awt.Dimension(877, 481));

        listBtn.add(jPanel2);
        listBtn.add(jPanel6);
        listBtn.add(jPanel7);
        listLabel.add(jLabel1);
        listLabel.add(jLabel5);
        listLabel.add(jLabel6);
        jPanel1.setBackground(new java.awt.Color(65, 103, 179));

        jPanel2.setBackground(new java.awt.Color(65, 103, 179));
        jPanel2.setPreferredSize(new java.awt.Dimension(175, 19));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickBtn1(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnterButton1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton1(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(65, 103, 179));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(121, 147, 201));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dịch bệnh COVID-19");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(65, 103, 179));
        jPanel6.setPreferredSize(new java.awt.Dimension(177, 45));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickBtn4(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnterButton4(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton4(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(121, 147, 201));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thông tin liên hệ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel7.setBackground(new java.awt.Color(65, 103, 179));
        jPanel7.setPreferredSize(new java.awt.Dimension(175, 45));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickBtn5(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnterButton5(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitButton5(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(121, 147, 201));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hỏi đáp khác");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mouseExitButton5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton5
        if (isChoosing != 2){
            jPanel7.setBackground(color3);
            jLabel6.setForeground(color4);
            jLabel6.setFont(new java.awt.Font("Arial", 0, 16));
        }
    }//GEN-LAST:event_mouseExitButton5

    private void mouseEnterButton5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnterButton5
        jPanel7.setBackground(color1);
        jLabel6.setForeground(color2);
        jLabel6.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_mouseEnterButton5

    private void mouseClickBtn5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickBtn5
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(color3);
            listLabel.get(isChoosing).setForeground(color4);
            listLabel.get(isChoosing).setFont(new java.awt.Font("Arial", 0, 16));
        }
        jPanel7.setBackground(color1);
        jLabel6.setForeground(color2);
        jLabel6.setFont(new java.awt.Font("Arial", 1, 16));
        jPanel5.removeAll();
        OtherQuestionPanel panel = new OtherQuestionPanel();
        panel.setBounds(0,0,877,436);
        jPanel5.add(panel);
        isChoosing = 2;
    }//GEN-LAST:event_mouseClickBtn5

    private void mouseExitButton4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton4
        if (isChoosing != 1){
            jPanel6.setBackground(color3);
            jLabel5.setForeground(color4);
            jLabel5.setFont(new java.awt.Font("Arial", 0, 16));
        }
    }//GEN-LAST:event_mouseExitButton4

    private void mouseEnterButton4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnterButton4
        jPanel6.setBackground(color1);
        jLabel5.setForeground(color2);
        jLabel5.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_mouseEnterButton4

    private void mouseClickBtn4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickBtn4
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(color3);
            listLabel.get(isChoosing).setForeground(color4);
            listLabel.get(isChoosing).setFont(new java.awt.Font("Arial", 0, 16));
        }
        jPanel5.removeAll();
        ContactPanel contactPanel = new ContactPanel();
        contactPanel.setBounds(0,0,877,436);
        jPanel5.add(contactPanel);
        jPanel6.setBackground(color1);
        jLabel5.setForeground(color2);
        jLabel5.setFont(new java.awt.Font("Arial", 1, 16));
        isChoosing = 1;
    }//GEN-LAST:event_mouseClickBtn4

    private void mouseExitButton1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitButton1
        if (isChoosing != 0){
            jPanel2.setBackground(color3);
            jLabel1.setForeground(color4);
            jLabel1.setFont(new java.awt.Font("Arial", 0, 16));
        }
    }//GEN-LAST:event_mouseExitButton1

    private void mouseEnterButton1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnterButton1
        jPanel2.setBackground(color1);
        jLabel1.setForeground(color2);
        jLabel1.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_mouseEnterButton1

    private void mouseClickBtn1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickBtn1
        if (isChoosing != -1){
            listBtn.get(isChoosing).setBackground(color3);
            listLabel.get(isChoosing).setForeground(color4);
            listLabel.get(isChoosing).setFont(new java.awt.Font("Arial", 0, 16));
        }
        jPanel5.removeAll();
        Covid19DiseasePanel covid19Panel = new Covid19DiseasePanel();
        covid19Panel.setBounds(0,0,877,436);
        jPanel5.add(covid19Panel);
        jPanel2.setBackground(color1);
        jLabel1.setForeground(color2);
        jLabel1.setFont(new java.awt.Font("Arial", 1, 16));
        isChoosing = 0;
    }//GEN-LAST:event_mouseClickBtn1


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
